# Site settings
title: oukohou
subtitle: oukohou's blog
keywords: oukohou
description: 我梦扬州，便想到扬州梦我。幸会。微信公众号：oukohou.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.oukohou.wang/" # 你的域名
page_no_title: "oukohou's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: oukohou
email: oukohou@outlook.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins: [jekyll-paginate]

# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

#markdown: redcarpet
#redcarpet:
#    extensions: ["fenced_code_blocks",
#                 "tables",
#                 "highlight",
#                 "strikethrough",
#                 "no_intra_emphasis",
#                 "with_toc_data"]

# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: about/
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # 友情链接
  - title: oukohou's github
    url: https://github.com/oukohou
#  - title:
#    url: http://jekyllcn.com/
  - title: Jekyll 博客系统
    url: http://jekyllcn.com/



# Google Analytics
ga_track_id: 'UA-126058460-1'            # Format: UA-xxxxxx-xx
ga_domain: www.oukohou.wang              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: Iv1.042c5629457a3528                            #生成的clientID
  clientSecret: 9e20585681a8218bd4b628f9d5d7cd9a8562f8d5    #生成的clientSecret
  repo: issue-support    #仓库名称
  owner: kohou-wang    #github用户名
  admin: kohou-wang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Code hub settings
codehub: # 代码仓库
  - title: Github
    url: https://github.com/oukohou
