# Site settings
title: oukohou
subtitle: oukohou's blog
keywords: oukohou
description: 我梦扬州，便想到扬州梦我。幸会。微信公众号：oukohou.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.oukohou.wang/" # 你的域名
page_no_title: "oukohou's blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: oukohou
email: oukohou@outlook.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins: [jekyll-paginate]
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks",
                 "tables",
                 "highlight",
                 "strikethrough",
                 "no_intra_emphasis",
                 "with_toc_data"]

# Pageinate settings
paginate: 8 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-tags
  - page: 留言
    directory: guestbook/
    icon: icon-guestbook
  - page: 关于
    directory: about.md
    icon: icon-about
#  - page: 订阅
#    directory: feed.xml
#    icon: icon-rss

# Link settings
links: # 友情链接
  - title: oukohou's github
    url: https://github.com/oukohou
#  - title:
#    url: http://jekyllcn.com/
  - title: Jekyll 博客系统
    url: http://jekyllcn.com/


# Code hub settings
codehub: # 代码仓库
  - title: Github
    url: https://github.com/oukohou
